### ISSUE TITLE
HttpUnixClient: potential hang

### ISSUE THREAD

**Issue by jpnurmi** [canonical/snapd.dart#34]
`HttpUnixClient._processContent()` looks similar to the one in `subiquity_client` so it probably has the same busy read loop issue: https://github.com/canonical/ubuntu-desktop-installer/pull/179.

https://github.com/canonical/snapd.dart/blob/main/lib/src/http_unix_client.dart#L199

**Comment by robert-ancell** [comment]
RIP HttpUnixClient! 62ae3dd532fce61f62d6bcc682211a635a942a0b
