### ISSUE TITLE
How to see if an app is classic?

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/snapd.dart#43]
Thanks for adding the classic option with https://github.com/canonical/snapd.dart/pull/42/commits/48614b1b698a7dea3a9c983578d8dd52374c403f

However I am not sure how to see if an app is classic or not to then forward this bool to the install method of the client
Eclipse is a classic snap but I do not see this information displayed int the Snap class
![grafik](https://user-images.githubusercontent.com/15329494/169547074-8a1b3415-59eb-4612-8fe2-aaa8054b8cd0.png)

Thanks in advance :smile_cat:

**Comment by robert-ancell** [comment]
Snaps were missing the confinement property - this should now be there in main!

**Comment by Feichtmeier** [comment]
Thank you so much!

**Comment by Feichtmeier** [comment]
@robert-ancell there is still some piece missing I think
upgraded and get from master
Now I can forward snap.confinment == SnapConfinment.classic
but it looks like snapd is still not seeing this "flag", even if forwarded:

![grafik](https://user-images.githubusercontent.com/15329494/169717369-6ce4bd81-a7fe-433a-bb66-cc5c0535f759.png)

**Comment by robert-ancell** [comment]
It seems there is a bug in snapd that is doesn't use the classic flag correctly when installing multiple snaps. I've switched snapd.dart to use the single snap API which is being used by snapd-glib https://github.com/canonical/snapd.dart/pull/45. I could then install eclipse by modifying the install example to set classic.

**Comment by Feichtmeier** [comment]
Works! Thank you! :dancers: 

![grafik](https://user-images.githubusercontent.com/15329494/169749494-de363bd4-c7e5-4ecf-87c3-9f3d0a79fb94.png)
