### ISSUE TITLE
Request: add "tracking" and or "installed" information

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/snapd.dart#53]
The tracks list only contains the list of tracks. The field channel only contains the name of the channel without the track. Combining either of this won't get you the combination to get the "tracking" or "installed" information. Combining any of this with the version also won't help because you can have the same version in multiple channels.

**Comment by robert-ancell** [comment]
trackingChannel property added in https://github.com/canonical/snapd.dart/pull/55

**Comment by robert-ancell** [comment]
I think you have all the available info now, but please re-open if not.

**Comment by Feichtmeier** [comment]
Thanks for the fast solution. Tried this right after but sadly the tracking string keeps being empty after a fresh snap returned by find by name :(

**Comment by robert-ancell** [comment]
Right - when you do a find you are getting information from the store, so this doesn't include any information about the locally installed state of this snap. You need to do both a `find()` (round trip to the server) and a `snaps()` call (checks local database) to get all the information you need. The latter will have `trackingChannel` set.

I'll add another method to get information on a single installed snap.

**Comment by robert-ancell** [comment]
Added `getSnap()` in https://github.com/canonical/snapd.dart/pull/57 and updated the documentation a little to be less confusing.
