### ISSUE TITLE
installedDate is only not null of the channel is stable

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/snapd.dart#54]
For example telegram-desktop installed from latest/edge has the installedDate set as null

![grafik](https://user-images.githubusercontent.com/15329494/171046082-6d4d562a-75b2-4804-819c-4921c0fe9081.png)

Whereas telegram.desktop installed from latest/stable has the installedDate field filled with a date
![grafik](https://user-images.githubusercontent.com/15329494/171046700-e105785b-9f02-4a8c-89bc-176e04b56873.png)

**Comment by robert-ancell** [comment]
Is both sets of information being taken from `SnapdClient.snaps()`? I checked here and both cases are returning an installDate for me. I've updated the info example to get and show this information - can you check that on your system?

**Comment by Feichtmeier** [comment]
Thank you so much @robert-ancell !

Now I think I pulled all the strings together :) Used the _localSnap and _storeSnap pattern from your example :+1: 
![grafik](https://user-images.githubusercontent.com/15329494/171132077-1a74867e-5ee0-4347-877d-68e863a2a83c.png)
