### ISSUE TITLE
Implement assertions

### ISSUE THREAD

**Issue by matthew-hagemann** [canonical/snapd.dart#99]
We have an issue in the [app-center](https://github.com/ubuntu/app-center) where ratings are returned for snap-id's, with no additional information to use to identify the snap with. 

One way to get snap details for a given snap-id is via the [Get/v2/assertions](https://snapcraft.io/docs/snapd-api#heading--assertions) endpoint. For example, given the snap-id: ZWyHJJiPBBfMKpaaKKrpSgAcupWkHWPz one can use the assertions endpoint to get the snap-declaration which contains the data we need:

```
$ curl -s --unix-socket /var/run/snapd.socket "http://localhost/v2/assertions/snap-declaration?series=16&remote=true&snap-id=ZWyHJJiPBBfMKpaaKKrpSgAcupWkHWPz"

type: snap-declaration
authority-id: canonical
revision: 1
series: 16
snap-id: ZWyHJJiPBBfMKpaaKKrpSgAcupWkHWPz
publisher-id: IEzHQPsJJcDJXVbfCdg5mh4cfFs7Xmhq
snap-name: blender
timestamp: 2019-07-26T14:11:18.638968Z
sign-key-sha3-384: BWDEoaqyr25nF5SNCvEv2v7QnM9QsfCc0PBMYD\_i2NGSQ32EF2d4D0hqUel3m8ul

AcLBUgQAAQoABgUCXTsKBgAATSsQAMOHPtByzTLahvARlep2v0whdmpBLNB0o/8nB4GGJTWp00hk
+X6HZBUq+D+PnFKO95TW7ezn5KRt7ZN8JXw0TabdccgQWtgxS6+Q3HxEHytFSqIQIM+49KHBC1ej
yelhnoJNCwzAr722lEzrOqjZrBM0QvIIxE67/JO3ucCPhawfUdDTaEx0+ZJCiCYSr365+4iZsp48
UHlKEXOYWLRp99aeBEtoHmArsnvnJJsnazYvOBz1dAw83hGl38AajAOl10Nb9zgYh1Z+ua5pNQFu
qdIt/Fx921XYMOM7Sb5cOKz/TfZMbVl5R61mIT5/pdJUiPF6XPt0rgocxQKq4a0LAFEVMk+V7Es/
mWU/fLkRJKbbJsFZYMas2q/MmGaCeH+BwItG8IHxn19tO3INANwTrxEE0xc4Phz9985ty8vcuWov
i5JtZeixT6vjL9eYKg2+JbqS2u3fBasC2SLXIGhFL182zqJwanLUsVVteSupP/zdfZNruUC+DhMZ
dXbkpMS4XcSdLB7jry3FJzKa0/yQdJKsYGS6bQ9cI4j6g6QECj8aQZNbqWsINwA5uCYaPuQ2mqyW
82/iMA6TJHKEUf1kYYfhqStT+ZlZg54nvoXlSGe19hZAqqvDq1RATimKf/pgV80xG/j+wQAT2ael
bE5QwvgcYfJMj92Gcz9GceQIUamX
```

We need to add this functionality to the client so that we can make use of it in the app-center

**Comment by robert-ancell** [comment]
It's weird that both the snap store and snapd don't have a method of getting information on a snap by id. No problem implementing this in snapd.dart, but I wonder if you need it - what's the case where you have a rating but not the associated snap information?

**Comment by matthew-hagemann** [comment]
Hi Robert. Currently when a user casts a thumbs up / down against a snap, the only identifier that is saved in the votes db entry is the snap-id. For most use cases that's fine, because you have the snap data already and want to look up a rating via the ratings service. 

Where we have run into a problem is for getting a "Top 10" [chart](https://github.com/ubuntu/app-center/issues/1497) from the ratings service, which will return the top X snaps with the highest ratings, but only has a snap-id as an identifier of who the rating belongs to, and we don't currently have a way of figuring out which snaps those id's correspond to.
